conky.config = {
	update_interval = 1,
	total_run_times = 0,
	double_buffer = true,
	no_buffers = true,
	override_utf8_locale = true,

	own_window = true,
	own_window_type = 'desktop',
	own_window_argb_visual = true,
	own_window_argb_value = 0,
	own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager,below',
	own_window_class = 'ConkyMarkets',
	own_window_title = 'ConkyMarkets',

	draw_outline = false,
	draw_borders = false,
	draw_shades = true,
	default_shade_color = '#000000',
	draw_graph_borders = false,
	border_width = 0,
	border_inner_margin = 0,

	use_xft = true,
	font = 'Candara:size=12',
	xftalpha = 1.0,
	default_color = 'c0c0c0',
	text_buffer_size = 2048,

	uppercase = false,
	out_to_ncurses = false,
	out_to_console = false,

	alignment = 'bottom_right',
	gap_x = 25,
	gap_y = 50,
	minimum_width = 168,
	minimum_height = 44,

	color1 = 'c0c0c0',
	color2 = '888888',
};

conky.text = [[
${image __HOME__/.conky/icons/tinkoff.png -p 0,2 -s 16x16}${alignr}${font Candara:size=12}${execpi 1 __PROJECT_DIR__/.venv/bin/python __PROJECT_DIR__/conky_markets.py stocks}${font}
${image __HOME__/.conky/icons/bitcoin.png -p 0,24 -s 16x16}${alignr}${font Candara:size=12}${execpi 1 __PROJECT_DIR__/.venv/bin/python __PROJECT_DIR__/conky_markets.py crypto}${font}
]];
